language: r
warnings_are_errors: true
sudo: required
# questo di sotto è per non crollare tutto servendo TK e senza server grafico
addons: apt: packages: - xvfb
script: - xvfb-run R CMD check *tar.gz --as-cran