#!/usr/bin/Rscript --vanilla --quiet

tex2pdf                    <- new.env()
tex2pdf$t2pdf_file         <- commandArgs(trailingOnly = TRUE)[1]
tex2pdf$t2pdf_noext        <- tools::file_path_sans_ext(tex2pdf$t2pdf_file)
tex2pdf$t2pdf_tex          <- paste(tex2pdf$t2pdf_noext, 'tex', sep = '.')
tex2pdf$t2pdf_pdf          <- paste(tex2pdf$t2pdf_noext, 'pdf', sep = '.')
tex2pdf$t2pdf_bibtex_cmd   <- paste("bibtex", tex2pdf$t2pdf_noext)
tex2pdf$t2pdf_pdflatex_cmd <- paste("pdflatex", tex2pdf$t2pdf_noext)
tex2pdf$t2pdf_okular_cmd   <- paste("okular", tex2pdf$t2pdf_pdf, '&')
attach(tex2pdf)
rm(tex2pdf)

## knitr
knitr::knit(input = t2pdf_file, output = t2pdf_tex, envir = new.env())

## standard Latex
system(t2pdf_pdflatex_cmd)
system(t2pdf_bibtex_cmd)
system(t2pdf_pdflatex_cmd)
system(t2pdf_pdflatex_cmd)
