#!/usr/bin/Rscript --vanilla --quiet

# usage: Rpackages_remove pkg1 pkg2 ..

pkgs <- commandArgs(trailingOnly = TRUE)
R_vrs <- with(R.Version(), strtrim(paste(major, minor, sep = '.'), 3))
R_userdir <- paste('~/R/x86_64-pc-linux-gnu-library', R_vrs, '', sep = '/')
remove.packages(pkgs = pkgs, lib = R_userdir)
