#!/usr/bin/Rscript --vanilla --quiet

template <- "#!/usr/bin/Rscript --vanilla --quiet

## rscript --a_character --a_logical FALSE --an_integer 2 --a_numeric
opts <- list(
    list(name = 'a_character' , default = 'hello'   , f = as.character),
    list(name = 'a_logical'   , default = 'TRUE'    , f = as.logical),
    list(name = 'an_integer'  , default = '2'       , f = as.integer),
    list(name = 'a_numeric'   , default = '1.5'     , f = as.numeric)
)
args   <- lbmisc::argparse(opts = opts)
"

f <- commandArgs(trailingOnly = TRUE)[1]
cat(template, file = f)
system(sprintf("chmod +x %s", f))
